defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m


version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - persist_to_workspace:
          root: .
          paths:
            - .

  cache_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Downloading dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  code_check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Performing static analysis
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports/code_check
      - save_cache:
          paths:
            - ~/.gradle
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}


  build_debug:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug apk
          command: ./gradlew assembleDebug
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - app/build/


  test_debug:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: deps-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Unit test application
          command: ./gradlew testDebugUnitTest
      - store_test_results:
          path: app/build/reports/tests/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: reports/tests/unit/debug


  approve:
    <<: *defaults
    steps:
      - run:
          command: echo Done!


workflows:
  version: 2

  # any commit
  build_and_test:
    jobs:
      - checkout_code
      - cache_dependencies:
          requires:
            - checkout_code
      - code_check:
          requires:
            - cache_dependencies
      - build_debug:
          requires:
            - cache_dependencies
      - test_debug:
          requires:
            - build_debug
      - approve:
          requires:
            - code_check
            - test_debug